/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.List;
import javax.sound.midi.Soundbank;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import logica.*;

/**
 *
 * @author davi1
 */
public class Ventana extends javax.swing.JFrame {
    static AdminTienda tienda = new AdminTienda();
    //Venta ventaAux = new Venta();
    List<Producto> venta = new ArrayList<Producto>();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setResizable(false);  //deshabilitar boton maximizar
        this.setLocationRelativeTo(null); //centrar ventana
        btnClienteBorrar.setVisible( false );
        btnProveedorBorrar.setVisible( false );
        btnProductoBorrar.setVisible( false );
        btnVentaBorrar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        nDocClienteVenta = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        codProductoVenta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cantidadProductoVenta = new javax.swing.JTextField();
        btnAgregarProductoVenta = new javax.swing.JButton();
        listaProductosVenta = new javax.swing.JList<>();
        btnVenta = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaVentas = new javax.swing.JList<>();
        btnVentaBorrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        codigoProducto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        precioProducto = new javax.swing.JTextField();
        cantidadProducto = new javax.swing.JTextField();
        nDocProveedorProducto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnProducto = new javax.swing.JButton();
        btnProductoBorrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nombreProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apellidoProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nDocProveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nomEmpresaProveedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        direccionProveedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        telefonoProveedor = new javax.swing.JTextField();
        btnProveedor = new javax.swing.JButton();
        btnProveedorBorrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProveedores = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        nombreCliente = new javax.swing.JTextField();
        apellidoCliente = new javax.swing.JTextField();
        nDocCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        btnClienteBorrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Tienda");

        jLabel15.setText("No. Documento cliente:");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Cod. Producto");

        jLabel17.setText("Catidad");

        btnAgregarProductoVenta.setText("Agregar");
        btnAgregarProductoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregarProductoVenta)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codProductoVenta)
                                .addComponent(cantidadProductoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))))
                    .addComponent(listaProductosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(codProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(cantidadProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarProductoVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaProductosVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnVenta.setText("Aceptar");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        listaVentas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaVentasValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(listaVentas);

        btnVentaBorrar.setText("Borrar");
        btnVentaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(nDocClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVentaBorrar)
                                .addGap(103, 103, 103)
                                .addComponent(btnVenta))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nDocClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVenta)
                            .addComponent(btnVentaBorrar)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ventas", jPanel1);

        jLabel10.setText("Nombre producto:");

        jLabel11.setText("Código producto:");

        jLabel12.setText("Precio:");

        jLabel13.setText("Cantidad:");

        jLabel14.setText("No. Documento proveedor:");

        btnProducto.setText("Agregar");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnProductoBorrar.setText("Borrar");
        btnProductoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoBorrarActionPerformed(evt);
            }
        });

        listaProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaProductosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaProductos);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnProductoBorrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProducto))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(nDocProveedorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nDocProveedorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProducto)
                            .addComponent(btnProductoBorrar))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Productos", jPanel2);

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido");

        jLabel6.setText("No. Documento");

        jLabel7.setText("Dirección:");

        jLabel8.setText("Nombre empresa");

        jLabel9.setText("Teléfono");

        btnProveedor.setText("Agregar");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        btnProveedorBorrar.setText("Borrar");
        btnProveedorBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorBorrarActionPerformed(evt);
            }
        });

        listaProveedores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaProveedoresValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaProveedores);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnProveedorBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProveedor))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(direccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(nomEmpresaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(nDocProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(apellidoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nDocProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomEmpresaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProveedorBorrar)
                            .addComponent(btnProveedor))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Proveedores", jPanel4);

        apellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoClienteActionPerformed(evt);
            }
        });

        nDocCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nDocClienteKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("No. documento");

        btnCliente.setText("Agregar");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        listaClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaClientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaClientes);

        btnClienteBorrar.setText("Borrar");
        btnClienteBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnClienteBorrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCliente))
                        .addComponent(nombreCliente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(apellidoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nDocCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nDocCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnClienteBorrar))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoClienteActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        try{
            if ( btnCliente.getText() == "Agregar" ){
                Cliente cli = new Cliente ();
                cli.setNombre( nombreCliente.getText() );
                cli.setApellido( apellidoCliente.getText() );
                cli.setNum_doc( Long.parseLong( nDocCliente.getText() ) );
                tienda.agregarCliente(cli);
                listarClientes();
                limpiarInputsCliente ();
            }else{
                Cliente cli = new Cliente ();
                cli.setNombre( nombreCliente.getText() );
                cli.setApellido( apellidoCliente.getText() );
                cli.setNum_doc( Long.parseLong( nDocCliente.getText() ) );
                tienda.actualizarCliente(listaClientes.getSelectedIndex() , cli );
                listarClientes();
                limpiarInputsCliente ();
                btnClienteBorrar.setVisible( false );
                btnCliente.setText( "Agregar" );
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnClienteActionPerformed

    private void nDocClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nDocClienteKeyTyped
        char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
   
    }//GEN-LAST:event_nDocClienteKeyTyped

    private void listaClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaClientesValueChanged
        if ( listaClientes.getSelectedIndex() >= 0 ){
            nombreCliente.setText( tienda.getClientes().get( listaClientes.getSelectedIndex() ).getNombre() );
            apellidoCliente.setText( tienda.getClientes().get( listaClientes.getSelectedIndex() ).getApellido() );
            nDocCliente.setText( String.valueOf( tienda.getClientes().get( listaClientes.getSelectedIndex() ).getNum_doc() ) );
            btnClienteBorrar.setVisible( true );
            btnCliente.setText( "Actualizar" );
        }
    }//GEN-LAST:event_listaClientesValueChanged

    private void btnClienteBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteBorrarActionPerformed
        tienda.borrarCliente(listaClientes.getSelectedIndex() );
        listarClientes();
        limpiarInputsCliente ();
        btnClienteBorrar.setVisible( false );
        btnCliente.setText( "Agregar" );
    }//GEN-LAST:event_btnClienteBorrarActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        try{
            if ( btnProveedor.getText() == "Agregar" ){
                Proveedor pro = new Proveedor ();
                pro.setNombre( nombreProveedor.getText() );
                pro.setApellido( apellidoProveedor.getText() );
                pro.setNum_doc( Long.parseLong( nDocProveedor.getText() ) );
                pro.setDireccion( direccionProveedor.getText() );
                pro.setNom_empresa(nomEmpresaProveedor.getText() );
                pro.setTelefono( Long.parseLong( telefonoProveedor.getText() ) );
                tienda.agregarProveedor(pro);
                listarProveedores();
                limpiarInputsProveedor();
            }else{
                Proveedor pro = new Proveedor ();
                pro.setNombre( nombreProveedor.getText() );
                pro.setApellido( apellidoProveedor.getText() );
                pro.setNum_doc( Long.parseLong( nDocProveedor.getText() ) );
                pro.setDireccion( direccionProveedor.getText() );
                pro.setNom_empresa(nomEmpresaProveedor.getText() );
                pro.setTelefono( Long.parseLong( telefonoProveedor.getText() ) );
                tienda.actualizarProveedor(listaProveedores.getSelectedIndex() , pro );
                listarProveedores();
                limpiarInputsProveedor();
                btnProveedorBorrar.setVisible( false );
                btnProveedor.setText( "Agregar" );
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnProveedorBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorBorrarActionPerformed
        tienda.borrarProveedor(listaProveedores.getSelectedIndex() );
        listarProveedores();
        limpiarInputsProveedor();
        btnProveedorBorrar.setVisible( false );
        btnProveedor.setText( "Agregar" );
    }//GEN-LAST:event_btnProveedorBorrarActionPerformed

    private void listaProveedoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaProveedoresValueChanged
        if ( listaProveedores.getSelectedIndex() >= 0 ){
            nombreProveedor.setText( tienda.getProveedores().get( listaProveedores.getSelectedIndex() ).getNombre() );
            apellidoProveedor.setText( tienda.getProveedores().get( listaProveedores.getSelectedIndex() ).getApellido() );
            nDocProveedor.setText( String.valueOf( tienda.getProveedores().get( listaProveedores.getSelectedIndex() ).getNum_doc() ) );
            direccionProveedor.setText( tienda.getProveedores().get( listaProveedores.getSelectedIndex() ).getDireccion() );
            nomEmpresaProveedor.setText( tienda.getProveedores().get( listaProveedores.getSelectedIndex() ).getNom_empresa() );
            telefonoProveedor.setText( String.valueOf( tienda.getProveedores().get( listaProveedores.getSelectedIndex() ).getTelefono() ) );
            btnProveedorBorrar.setVisible( true );
            btnProveedor.setText( "Actualizar" );
        }
    }//GEN-LAST:event_listaProveedoresValueChanged

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        try{
            if ( btnProducto.getText() == "Agregar" ){
                Producto pro = new Producto ();
                pro.setNombre( nombreProducto.getText() );
                pro.setCodigo( codigoProducto.getText() );
                
                Proveedor prove = tienda.validarProveedor( Long.parseLong( nDocProveedorProducto.getText() ) );
                if ( prove != null ){
                    pro.setProveedor(prove);
                }else{
                    JOptionPane.showMessageDialog(null, "No existe proveedor con ese no. de Documento", "Error", 
                    JOptionPane.WARNING_MESSAGE);
                    throw new IndexOutOfBoundsException();
                }
                
                pro.setPrecio( Double.parseDouble( precioProducto.getText() ) );
                pro.setCantidad( Integer.parseInt( cantidadProducto.getText() ) );
                tienda.agregarProducto(pro);
                listarProductos();
                limpiarInputsProductos();
            }else{
                Producto pro = new Producto ();
                pro.setNombre( nombreProducto.getText() );
                pro.setCodigo( codigoProducto.getText() );
                
                Proveedor prove = tienda.validarProveedor( Long.parseLong( nDocProveedorProducto.getText() ) );
                if ( prove != null ){
                    pro.setProveedor(prove);
                }else{
                    JOptionPane.showMessageDialog(null, "No existe proveedor con ese no. de Documento", "Error", 
                    JOptionPane.WARNING_MESSAGE);
                    throw new IndexOutOfBoundsException();
                }
                
                pro.setPrecio( Double.parseDouble( precioProducto.getText() ) );
                pro.setCantidad( Integer.parseInt( cantidadProducto.getText() ) );
                tienda.actualizarProducto( listaProductos.getSelectedIndex() , pro );
                listarProductos();
                limpiarInputsProductos();
                btnProductoBorrar.setVisible( false );
                btnProducto.setText( "Agregar" );
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnProductoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoBorrarActionPerformed
        tienda.borrarProducto(listaProductos.getSelectedIndex() );
        listarProductos();
        limpiarInputsProductos();
        btnProductoBorrar.setVisible( false );
        btnProducto.setText( "Agregar" );
    }//GEN-LAST:event_btnProductoBorrarActionPerformed

    private void listaProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaProductosValueChanged
        if ( listaProductos.getSelectedIndex() >= 0 ){
            nombreProducto.setText( tienda.getProductos().get( listaProductos.getSelectedIndex() ).getNombre() );
            codigoProducto.setText( String.valueOf( tienda.getProductos().get( listaProductos.getSelectedIndex() ).getCodigo() ) );
            nDocProveedorProducto.setText( String.valueOf( tienda.getProductos().get( listaProductos.getSelectedIndex() ).getProveedor().getNum_doc() ) );
            cantidadProducto.setText( String.valueOf( tienda.getProductos().get( listaProductos.getSelectedIndex() ).getCantidad() ) );
            precioProducto.setText( String.valueOf( tienda.getProductos().get( listaProductos.getSelectedIndex() ).getPrecio() ) );
            btnProductoBorrar.setVisible( true );
            btnProducto.setText( "Actualizar" );
        }
    }//GEN-LAST:event_listaProductosValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listarProductos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarProductoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoVentaActionPerformed
        try{
            Producto pro = tienda.validarProducto( codProductoVenta.getText() );
            Producto aux = new Producto();
            if ( pro != null ){
                if ( pro.getCantidad() >= Integer.parseInt( cantidadProductoVenta.getText() ) ){
                    aux.setCantidad(Integer.parseInt( cantidadProductoVenta.getText() ) );
                    aux.setCodigo( pro.getCodigo() );
                    aux.setNombre( pro.getNombre() );
                    aux.setPrecio( pro.getPrecio() );
                    venta.add(aux);
                    tienda.ajustarCantidadProducto(pro.getCodigo(), aux.getCantidad() );
                    limpiarInputsVentaProductos();
                    listarVentasProductos();
                    listarProductos();
                }else{
                    JOptionPane.showMessageDialog(null, "Cantidad de producto requerida no está disponible", "Error", 
                    JOptionPane.WARNING_MESSAGE); 
                }
            }else{
               JOptionPane.showMessageDialog(null, "Producto no existe", "Error", 
                    JOptionPane.WARNING_MESSAGE); 
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarProductoVentaActionPerformed

    private void listaVentasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaVentasValueChanged
        if ( listaVentas.getSelectedIndex() >= 0 ){
            btnVentaBorrar.setVisible( true );
            btnAgregarProductoVenta.setVisible( false );
            btnVenta.setText( "Cancelar" );
            venta = tienda.getVentas().get( listaVentas.getSelectedIndex() ).getProductos();
            listarVentasProductos();
        }
    }//GEN-LAST:event_listaVentasValueChanged

    private void btnVentaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaBorrarActionPerformed
        tienda.borrarVenta( listaVentas.getSelectedIndex() );
        listarVentas();
        btnVentaBorrar.setVisible( false );
        btnAgregarProductoVenta.setVisible( true );
        btnVenta.setText( "Aceptar" );
        venta = new ArrayList<Producto>();
        listarVentasProductos();
    }//GEN-LAST:event_btnVentaBorrarActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        try{
            if ( btnVenta.getText() == "Aceptar" ){
                Venta ven = new Venta ();
                
                Cliente cli = tienda.validarCliente( Long.parseLong( nDocClienteVenta.getText() ) );
                if ( cli != null ){
                    ven.setCliente(cli);
                }else{
                    JOptionPane.showMessageDialog(null, "No existe cliente ese no. de Documento", "Error", 
                    JOptionPane.WARNING_MESSAGE);
                    throw new IndexOutOfBoundsException();
                }
                
                ven.setCodVenta( tienda.getVentas().size() + 1 );
                ven.setProductos( venta );
                venta = new ArrayList<Producto>();
                listarVentasProductos();
                tienda.agregarVenta(ven);
                listarVentas();
                limpiarInputsVenta();
                
                Factura fact = new Factura(new javax.swing.JFrame(), true, ven.generarFactura());
                fact.setVisible(true);
            }else{
                venta = new ArrayList<Producto>();
                limpiarInputsVentaProductos();
                limpiarInputsVenta();
                listarVentasProductos();
                btnVenta.setText( "Aceptar" );
                btnVentaBorrar.setVisible(false);
                btnAgregarProductoVenta.setVisible( true );
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    private void listarClientes (){
        DefaultListModel modelo = new DefaultListModel();
        for ( int i=0; i<tienda.getClientes().size(); i++ ){
            modelo.addElement(tienda.getClientes().get(i).toString()); 
        }
        listaClientes.setModel(modelo);
    }
    
    private void limpiarInputsCliente (){
        nombreCliente.setText("");
        apellidoCliente.setText("");
        nDocCliente.setText("");
    }
    
    private void listarProveedores (){
        DefaultListModel modelo = new DefaultListModel();
        for ( int i=0; i<tienda.getProveedores().size(); i++ ){
            modelo.addElement(tienda.getProveedores().get(i).toString()); 
        }
        listaProveedores.setModel(modelo);
    }
    
    private void limpiarInputsProveedor (){
        nombreProveedor.setText("");
        apellidoProveedor.setText("");
        nDocProveedor.setText("");
        nomEmpresaProveedor.setText("");
        direccionProveedor.setText("");
        telefonoProveedor.setText("");
    }
    
    private void listarProductos (){
        DefaultListModel modelo = new DefaultListModel();
        for ( int i=0; i<tienda.getProductos().size(); i++ ){
            modelo.addElement(tienda.getProductos().get(i).toString()); 
        }
        listaProductos.setModel(modelo);
    }
    
    private void limpiarInputsProductos(){
        nombreProducto.setText("");
        codigoProducto.setText("");
        nDocProveedorProducto.setText("");
        precioProducto.setText("");
        cantidadProducto.setText("");
    }
    
    private void listarVentas (){
        DefaultListModel modelo = new DefaultListModel();
        for ( int i=0; i<tienda.getVentas().size(); i++ ){
            modelo.addElement(tienda.getVentas().get(i).toString()); 
        }
        listaVentas.setModel(modelo);
    }
    
    private void listarVentasProductos (){
        DefaultListModel modelo = new DefaultListModel();
        for ( int i=0; i<venta.size(); i++ ){
            modelo.addElement(venta.get(i).toString()); 
        }
        listaProductosVenta.setModel(modelo);
    }
    
    private void limpiarInputsVenta(){
        nDocClienteVenta.setText("");
    }
    
    private void limpiarInputsVentaProductos(){
        codProductoVenta.setText("");
        cantidadProductoVenta.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JTextField apellidoProveedor;
    private javax.swing.JButton btnAgregarProductoVenta;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnClienteBorrar;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProductoBorrar;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnProveedorBorrar;
    private javax.swing.JButton btnVenta;
    private javax.swing.JButton btnVentaBorrar;
    private javax.swing.JTextField cantidadProducto;
    private javax.swing.JTextField cantidadProductoVenta;
    private javax.swing.JTextField codProductoVenta;
    private javax.swing.JTextField codigoProducto;
    private javax.swing.JTextField direccionProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listaClientes;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JList<String> listaProductosVenta;
    private javax.swing.JList<String> listaProveedores;
    private javax.swing.JList<String> listaVentas;
    private javax.swing.JTextField nDocCliente;
    private javax.swing.JTextField nDocClienteVenta;
    private javax.swing.JTextField nDocProveedor;
    private javax.swing.JTextField nDocProveedorProducto;
    private javax.swing.JTextField nomEmpresaProveedor;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField nombreProveedor;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JTextField telefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
